---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: ha
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 8124
      targetPort: 8124
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.moria-lab.com`)
      kind: Rule
      services:
        - name: home-assistant
          port: 8124
  tls:
    secretName: moria-lab-cert