apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ingress.yaml
  - prometheusrules/gitops-cert-manager-expiration-prometheus.yaml
  - prometheusrules/longhorn-storage-alerts.yaml
  - prometheusrules/traefik-alerts.yaml
  - alertmanagerconfig-discord.yaml 