apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ingress.yaml
  - prometheusrules/gitops-cert-manager-expiration-prometheus.yaml
  - prometheusrules/gitops-cert-manager-expiration-loki.yaml
  - prometheusrules/gitops-cert-manager-errors.yaml 