apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: z2m
  namespace: zigbee
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`z2m.moria-lab.com`)
      kind: Rule
      services:
        - name: z2m
          port: 8080
  tls:
    secretName: moria-lab-cert
