apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zwave
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`zwave.moria-lab.com`)
      kind: Rule
      services:
        - name: zwave
          port: 80
  tls: {}
