zigbee2mqtt:
  serial:
    port: "tcp://192.168.10.36:6638"
  mqtt:
    server: "mqtt://192.168.10.79:1883"
  homeassistant:
    enabled: true
  frontend:
    port: 8080
    enabled: true
  permit_join: false

persistence:
  enabled: true
  size: 2Gi
  storageClass: longhorn

securityContext:
  privileged: true

nodeSelector:
  node-role: home-assistant

env:
  - name: TZ
    value: America/New_York 