apiVersion: v1
kind: Service
metadata:
  name: hubitat-ui
spec:
  ports:
    - name: hubitat-ui
      protocol: TCP
      port: 80
  type: ExternalName
  externalName: 192.168.0.91
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubitat-ui
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hubitat.moria-lab.com`)
      kind: Rule
      services:
        - name: hubitat-ui
          port: 80
  tls: {}