apiVersion: v1
kind: Service
metadata:
  name: proxmox-ui
spec:
  ports:
    - name: proxmox-ui
      protocol: TCP
      port: 443
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-ui
subsets:
  - addresses:
      - ip: 192.168.10.6
    ports:
      - name: http
        port: 8006
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ui
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxmox.moria-lab.com`)
      kind: Rule
      services:
        - name: proxmox-ui
          port: 443
          serversTransport: selfsigned
  tls:
    secretName: moria-lab-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: selfsigned
spec:
  insecureSkipVerify: true