apiVersion: v1
kind: Service
metadata:
  name: rancher-ui
spec:
  ports:
    - name: rancher-ui
      protocol: TCP
      port: 443
      targetPort: 8006
  type: ExternalName
  externalName: 192.168.10.202.sslip.io
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ui
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.moria-lab.com`)
      kind: Rule
      services:
        - name: rancher-ui
          port: 443
  tls:
    secretName: moria-lab-cert