defaultNamespace: monitoring
helm:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 79.0.1
  valuesFiles:
  - ./values.yaml
  releaseName: prometheus-community
kustomize:
  dir: overlays/dev