defaultNamespace: longhorn-system
helm:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: v1.10.0
  releaseName: longhorn
  values:
    persistence:
      defaultClassReplicaCount: 2
kustomize:
  dir: overlays/dev
diff:
  comparePatches:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: engineimages.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nodes.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: volumes.longhorn.io
    operations:
    - {"op": "replace", "path": "/status"}